/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import javax.swing.*;
import java.awt.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import modelo.OrdemServico;
import servico.OrdemServicoServico;
import servico.VeiculoServico;

public class TelaOrdemServicoForm extends JDialog {
    private OrdemServicoServico ordemServicoServico;
    private VeiculoServico veiculoServico;
    private OrdemServico ordemServico;
    private boolean editando;
    /**
     * Creates new form TelaOrdemServicoForm
     */
     public TelaOrdemServicoForm(Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Nova Ordem de Serviço");
        ordemServicoServico = new OrdemServicoServico();
        veiculoServico = new VeiculoServico();
        ordemServico = new OrdemServico();
        initComponents();
        configurarComponentes();
    }

    public TelaOrdemServicoForm(Frame parent, boolean modal, int idOs) {
        super(parent, modal);
        setTitle("Editar Ordem de Serviço");
        ordemServicoServico = new OrdemServicoServico();
        veiculoServico = new VeiculoServico();
        editando = true;
        initComponents();
        configurarComponentes();
        carregarOrdemServico(idOs);
    }

    private void configurarComponentes() {
        cboStatus.setModel(new DefaultComboBoxModel<>(new String[]{
            "ABERTA", "EM_ANDAMENTO", "CONCLUIDA", "CANCELADA"
        }));
        
        btnCancelar.addActionListener(e -> dispose());
        
        txtValorPago.addActionListener(e -> calcularDiferenca());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtPlacaVeiculo = new javax.swing.JTextField();
        txtValorTotal = new javax.swing.JTextField();
        txtDataEntrada = new javax.swing.JFormattedTextField();
        txtHoraInicio = new javax.swing.JFormattedTextField();
        txtPrevisaoEntrega = new javax.swing.JFormattedTextField();
        cboStatus = new javax.swing.JComboBox<>();
        txtValorPago = new javax.swing.JTextField();
        txtDiferenca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Placa do Veiculo:");

        jLabel2.setText("Valor Total:");

        jLabel3.setText("Data de Entrada:");

        jLabel4.setText("Hora de Inicio:");

        jLabel5.setText("Previsão de Entrega:");

        jLabel6.setText("Status:");

        jLabel7.setText("Valor Pago:");

        jLabel8.setText("Diferença:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataEntrada))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHoraInicio))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrevisaoEntrega))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorPago))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiferenca)))
                .addContainerGap(712, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrevisaoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDiferenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       if (!validarCampos()) {
            return;
        }

        ordemServico.setPlacaVeiculo(txtPlacaVeiculo.getText());
        ordemServico.setValorTotal(Double.parseDouble(txtValorTotal.getText()));
        ordemServico.setDataEntrada(LocalDate.parse(txtDataEntrada.getText()));
        ordemServico.setHoraInicio(LocalTime.parse(txtHoraInicio.getText()));
        ordemServico.setPrevisaoEntrega(LocalDateTime.parse(txtPrevisaoEntrega.getText()));
        ordemServico.setStatus(cboStatus.getSelectedItem().toString());
        ordemServico.setValorPago(Double.parseDouble(txtValorPago.getText()));
        ordemServico.setDiferenca(Double.parseDouble(txtDiferenca.getText()));

        try {
            ordemServicoServico.salvar(ordemServico);
            JOptionPane.showMessageDialog(this, 
                "Ordem de Serviço salva com sucesso!", 
                "Sucesso", 
                JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao salvar OS: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed
 private void calcularDiferenca() {
        try {
            double valorTotal = Double.parseDouble(txtValorTotal.getText());
            double valorPago = Double.parseDouble(txtValorPago.getText());
            double diferenca = valorTotal - valorPago;
            txtDiferenca.setText(String.format("%.2f", diferenca));
        } catch (NumberFormatException e) {
            txtDiferenca.setText("0.00");
        }
    }

    private void carregarOrdemServico(int idOs) {
        ordemServico = ordemServicoServico.buscarPorId(idOs);
        if (ordemServico != null) {
            txtPlacaVeiculo.setText(ordemServico.getPlacaVeiculo());
            txtValorTotal.setText(String.format("%.2f", ordemServico.getValorTotal()));
            txtDataEntrada.setText(ordemServico.getDataEntrada().toString());
            txtHoraInicio.setText(ordemServico.getHoraInicio().toString());
            txtPrevisaoEntrega.setText(ordemServico.getPrevisaoEntrega().toString());
            cboStatus.setSelectedItem(ordemServico.getStatus());
            txtValorPago.setText(String.format("%.2f", ordemServico.getValorPago()));
            txtDiferenca.setText(String.format("%.2f", ordemServico.getDiferenca()));
        }
    }
     private boolean validarCampos() {
        if (txtPlacaVeiculo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe a placa do veículo!");
            txtPlacaVeiculo.requestFocus();
            return false;
        }
        try {
            Double.parseDouble(txtValorTotal.getText());
            Double.parseDouble(txtValorPago.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Valores inválidos!");
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOrdemServicoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOrdemServicoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOrdemServicoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOrdemServicoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaOrdemServicoForm dialog = new TelaOrdemServicoForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JFormattedTextField txtDataEntrada;
    private javax.swing.JTextField txtDiferenca;
    private javax.swing.JFormattedTextField txtHoraInicio;
    private javax.swing.JTextField txtPlacaVeiculo;
    private javax.swing.JFormattedTextField txtPrevisaoEntrega;
    private javax.swing.JTextField txtValorPago;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
