/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import javax.swing.*;
import java.awt.*;

public class TelaPrincipal extends JFrame {

    public TelaPrincipal() {
        super("Sistema de Gestão de Oficina");
        configurarBotoes();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    private void configurarBotoes() {
        JPanel painelBotoes = new JPanel(new GridLayout(3, 2, 10, 10));
        painelBotoes.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        JButton btnClientes = new JButton("Clientes");
        JButton btnVeiculos = new JButton("Veículos");
        JButton btnServicos = new JButton("Serviços");
        JButton btnPecas = new JButton("Peças");
        JButton btnOrdemServico = new JButton("Ordem de Serviço");
        JButton btnOrcamentos = new JButton("Orçamentos");

        // Configurando ações dos botões
        btnClientes.addActionListener(e -> new TelaClientes().setVisible(true));
        btnVeiculos.addActionListener(e -> new TelaVeiculos().setVisible(true));
        btnServicos.addActionListener(e -> new TelaServico().setVisible(true));
        btnPecas.addActionListener(e -> new TelaPecas().setVisible(true));
        btnOrdemServico.addActionListener(e -> new TelaOrdemServico().setVisible(true));
        btnOrcamentos.addActionListener(e -> new TelaOrcamentos().setVisible(true));

        // Adicionando botões ao painel
        painelBotoes.add(btnClientes);
        painelBotoes.add(btnVeiculos);
        painelBotoes.add(btnServicos);
        painelBotoes.add(btnPecas);
        painelBotoes.add(btnOrdemServico);
        painelBotoes.add(btnOrcamentos);

        // Adicionando painel de botões ao centro da tela
        add(painelBotoes, BorderLayout.CENTER);

        // Configurações básicas da janela
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(800, 600);
        setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }

        EventQueue.invokeLater(() -> {
            new TelaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
