/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import persistencia.ClienteDAO;
import java.util.List;

public class TelaClientes extends javax.swing.JFrame {
     private DefaultTableModel modeloTabela;
    private ClienteDAO clienteDAO;
    
    public TelaClientes() {
        initComponents();
        configurarTabela();
        clienteDAO = new ClienteDAO();
        carregarDados();
    }
    
    private void configurarTabela() {
        String[] colunas = {
            "ID", "Tipo", "Nome", "Telefone", "Logradouro", "Número", 
            "Complemento", "Email", "CPF", "CNPJ", "Contato", "Inscrição Estadual"
        };
        modeloTabela = new DefaultTableModel(colunas, 0);
        tabela.setModel(modeloTabela);
        
        tabela.getColumnModel().getColumn(0).setPreferredWidth(50);  // ID
        tabela.getColumnModel().getColumn(1).setPreferredWidth(70);  // Tipo
        tabela.getColumnModel().getColumn(2).setPreferredWidth(200); // Nome
        tabela.getColumnModel().getColumn(3).setPreferredWidth(100); // Telefone
        tabela.getColumnModel().getColumn(4).setPreferredWidth(200); // Logradouro
        tabela.getColumnModel().getColumn(5).setPreferredWidth(70);  // Número
        tabela.getColumnModel().getColumn(6).setPreferredWidth(150); // Complemento
        tabela.getColumnModel().getColumn(7).setPreferredWidth(150); // Email
        tabela.getColumnModel().getColumn(8).setPreferredWidth(100); // CPF
        tabela.getColumnModel().getColumn(9).setPreferredWidth(100); // CNPJ
        tabela.getColumnModel().getColumn(10).setPreferredWidth(150); // Contato
        tabela.getColumnModel().getColumn(11).setPreferredWidth(120); // Inscrição
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNovo.setText("Novo Cliente");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnNovo)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnAtualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>
private void carregarDados() {
    while (modeloTabela.getRowCount() > 0) {
        modeloTabela.removeRow(0);
    }
    
    List<Cliente> clientes = clienteDAO.listarTodos();
    for (Cliente c : clientes) {
        modeloTabela.addRow(new Object[]{
            c.getIdCliente(),
            c.getTipoCliente(),
            c.getNome(),
            c.getTelefone(),
            c.getLogradouro(),
            c.getNumero(),
            c.getComplemento(),
            c.getEmail(),
            c.getCpf(),
            c.getCnpj(),
            c.getContato(),
            c.getInscricaoEstadual()
        });
    }
}
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {                                        
        TelaClienteForm form = new TelaClienteForm(this, true);
        form.setVisible(true);
        carregarDados();
    }                                       

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {                                          
 int linha = tabela.getSelectedRow();
    if (linha >= 0) {
        int id = (int) tabela.getValueAt(linha, 0);
        TelaClienteForm form = new TelaClienteForm(this, true, id);
        form.setVisible(true);
        carregarDados();
    } else {
        JOptionPane.showMessageDialog(this, 
            "Selecione um cliente para editar",
            "Editar Cliente",
            JOptionPane.WARNING_MESSAGE);
        
        }    }                                         

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {                                           
       int linha = tabela.getSelectedRow();
    if (linha >= 0) {
        int id = (int) tabela.getValueAt(linha, 0);
        int confirma = JOptionPane.showConfirmDialog(this,
            "Confirma a exclusão do cliente selecionado?",
            "Excluir Cliente",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if (confirma == JOptionPane.YES_OPTION) {
            clienteDAO.excluir(id);
            carregarDados();
            JOptionPane.showMessageDialog(this,
                "Cliente excluído com sucesso!",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this,
            "Selecione um cliente para excluir",
            "Excluir Cliente",
            JOptionPane.WARNING_MESSAGE);
    }
    }             //GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable modeloTabela;
    // End of variables declaration//GEN-END:variables
}
