/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import forms.TelaOrdemServicoForm;
import java.awt.BorderLayout;
import java.awt.Frame;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import modelo.OrdemServico;
import servico.OrdemServicoServico;
import java.util.List;
import java.time.format.DateTimeFormatter;

public class TelaOrdemServico extends JInternalFrame {
    private DefaultTableModel modeloTabela;
    private OrdemServicoServico ordemServicoServico;
    

    public TelaOrdemServico() {
        super("Gestão de Ordens de Serviço", false, true, false, true);
        ordemServicoServico = new OrdemServicoServico();
        setClosable(true);
        setMaximizable(true);
        setIconifiable(true);
        setResizable(true);
        setLayout(new BorderLayout());
        initComponents();
        configurarTabela();
        carregarDados();
        pack();
    }

    private void configurarTabela() {
        String[] colunas = {
        "ID OS", "Placa Veículo", "Valor Total", "Data Entrada", 
        "Hora Início", "Previsão Entrega", "Status", "Valor Pago", "Diferença"
    };
    
    modeloTabela = new DefaultTableModel(colunas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    tabela.setModel(modeloTabela);
    tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    tabela.getColumnModel().getColumn(0).setPreferredWidth(70);   // ID OS
    tabela.getColumnModel().getColumn(1).setPreferredWidth(100);  // Placa Veículo
    tabela.getColumnModel().getColumn(2).setPreferredWidth(100);  // Valor Total
    tabela.getColumnModel().getColumn(3).setPreferredWidth(100);  // Data Entrada
    tabela.getColumnModel().getColumn(4).setPreferredWidth(80);   // Hora Início
    tabela.getColumnModel().getColumn(5).setPreferredWidth(120);  // Previsão Entrega
    tabela.getColumnModel().getColumn(6).setPreferredWidth(100);  // Status
    tabela.getColumnModel().getColumn(7).setPreferredWidth(100);  // Valor Pago
    tabela.getColumnModel().getColumn(8).setPreferredWidth(100);  // Diferença
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        btnNovo.setText("Nova Ordem de Serviço");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar Ordem");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        TelaOrdemServicoForm form = new TelaOrdemServicoForm((Frame)evt.getSource(), true);
        form.setVisible(true);
        carregarDados();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int linha = tabela.getSelectedRow();
    if (linha >= 0) {
        int idOs = (int) tabela.getValueAt(linha, 0);
        
        // Obter o Frame ancestral usando SwingUtilities
        Frame parentFrame = (Frame) SwingUtilities.getWindowAncestor(this);
        
        TelaOrdemServicoForm form = new TelaOrdemServicoForm(parentFrame, true, idOs);
        form.setVisible(true);
        carregarDados();
    } else {
        JOptionPane.showMessageDialog(this, 
            "Selecione uma ordem de serviço para editar",
            "Editar OS",
            JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnEditarActionPerformed
private void carregarDados() {
         modeloTabela.setRowCount(0);
    List ordens = ordemServicoServico.listarTodos();
    DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm");
    DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

    for (Object ordem : ordens.toArray()) {
        OrdemServico os = (OrdemServico) ordem;
        modeloTabela.addRow(new Object[]{
            os.getIdOs(),
            os.getPlacaVeiculo(),
            String.format("R$ %.2f", os.getValorTotal()),
            os.getDataEntrada().format(dateFormatter),
            os.getHoraInicio().format(timeFormatter),
            os.getPrevisaoEntrega().format(dateTimeFormatter),
            os.getStatus(),
            String.format("R$ %.2f", os.getValorPago()),
            String.format("R$ %.2f", os.getDiferenca())
        });
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaOrdemServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
